development:
  adapter: postgresql
  database: sciencestore_dev
  host: localhost
  min_messages: warning
  username:

test:
  adapter: postgresql
  database: sciencestore_test
  host: localhost
  min_messages: warning
  username: